[package]
name = "vela"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
logger = { path = "../src/infrastructure/logger" }
config = { path = "../src/infrastructure/config" }
