[package]
name = "vela"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"

# 系统依赖
loggerx = { package = "logger", path = "../src/infrastructure/logger" }
cachex = { package = "cache", path = "../src/infrastructure/cache" }
configx = { package = "config", path = "../src/infrastructure/config" }
