[package]
name = "vela"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"


# 系统依赖
infrastructurex = { package = "infrastructure", path = "../src/infrastructure" }
commonx = { package = "common", path = "../src/common" }
interfacesx = { package = "interfaces", path = "../src/interfaces" }
