[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
serde_variant = "0.1.3"
serde_yaml = "0.9.34-deprecated"
common = { path = "../../common" }
