server:
  port: 36002
  host: 0.0.0.0
  # The directory where the static files will be served from.
  static_dir: data/static
  # The directory where the web files will be served from.
  web_dir: data/web
  # The directory where the upload files will be served from.
  upload_dir: data/upload
   # SSl configuration
  ssl:
    enable: false
    key: data/ssl/key.pem
    cert: data/ssl/cert.pem
  middlewares:
    logger:
      enable: true
    # when your code is panicked, the request still returns 500 status code.
    catch_panic:
      # Enable/Disable the middleware.
      enable: true
    # Timeout for incoming requests middleware. requests that take more time from the configuration will cute and 408 status code will returned.
    timeout_request:
      # Enable/Disable the middleware.
      enable: true
      # Duration time in milliseconds.
      timeout: 60000
    cors:
      enable: true
    limit_payload: 50mb

logger:
  enable: true
  level: trace
  log_dir: logs
  web_file_name: access
  api_file_name: api
  format: compact  


cache:
  # Cache type, options: redis, memory
  cache_type: redis
  namespace: vela  
  pool_size: 17
  # Queue Configuration
  url: redis://:ymDT@rediS2pwD@127.0.0.1:6666/12 

# genid 雪花id
snowgenera:
  # 机器ID
  machine_id: 1001
  # 机器节点
  node_id: 1

database:
# 核心：PostgreSQL 连接字符串（Sea-ORM 直接解析）
# 格式：postgres://用户名:密码@主机:端口/数据库名
# 场景1：本地无密码（你之前的PG环境，推荐）
# DATABASE_URL=postgres://postgres@localhost:5432/sea_orm_demo
# 场景2：本地有密码（替换为你的PG密码）
# DATABASE_URL=postgres://postgres:你的密码@localhost:5432/sea_orm_demo
# 场景3：远程PG库（如云服务器/RDS）
# DATABASE_URL=postgres://postgres:你的密码@192.168.1.100:5432/sea_orm_demo
  # uri: mysql://root:12345678@localhost:3306/vela
  uri: postgres://postgres:12345678@localhost:5432/vela
  # When enabled, the sql query will be logged.
  enable_logging: true
  # Set the timeout duration when acquiring a connection.
  connect_timeout: 60000
  # Set the idle duration before closing a connection.
  idle_timeout: 5000
  # Minimum number of connections for a pool.
  min_connections: 1
  # Maximum number of connections for a pool.
  max_connections: 20
  # Run migration up when application loaded
  auto_migrate: true
  # Truncate database when application loaded. This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_truncate: false
  # Recreating schema when application loaded.  This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_recreate: false   

# Authentication Configuration
auth:
  # JWT authentication
  jwt:
    # Secret key for token generation and verification
    secret: arxWd8PS123rtkl32QVE4Mn6T89Sl
    # Token expiration time in seconds
    expiration: 604800 # 7 days

# Worker Configuration
workers:
  queue:
    - default
  sched_queue:
    - retry
    - schedule
  num_workers: 1